# Generated by Django 5.2.4 on 2025-11-03 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Player', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('level_reached', models.IntegerField(default=1)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('words_captured', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capture Game Session',
                'verbose_name_plural': 'Capture Game Sessions',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapturePartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun')], max_length=20, unique=True)),
                ('description', models.TextField(help_text='Kid-friendly description')),
                ('hint_text', models.CharField(help_text='Hint for kids', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capture Part of Speech',
                'verbose_name_plural': 'Capture Parts of Speech',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ColorSplashLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('grid_size', models.IntegerField(default=4)),
                ('required_matches', models.IntegerField(default=4)),
                ('time_limit', models.IntegerField(default=180)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='ColorSplashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('time_elapsed', models.IntegerField(default=0)),
                ('game_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FruitColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('hex_color', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Fruit Colors',
            },
        ),
        migrations.CreateModel(
            name='GameEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('preview_time', models.IntegerField(default=2000)),
                ('required_pairs', models.IntegerField(default=2)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('moves', models.IntegerField(default=0)),
                ('matched_pairs', models.IntegerField(default=0)),
                ('cards_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('level_reached', models.IntegerField(default=1)),
                ('words_found', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Game Session',
                'verbose_name_plural': 'Search Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchWordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (3-6 years)'), ('medium', 'Medium (7-9 years)'), ('hard', 'Hard (10-12 years)')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Word Category',
                'verbose_name_plural': 'Search Word Categories',
                'ordering': ['difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SentenceBuilderLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('sentences_required', models.IntegerField(default=3)),
                ('time_limit', models.IntegerField(default=180)),
                ('points_per_sentence', models.IntegerField(default=10)),
                ('unlock_score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('milestone', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceBuilderGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('current_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('sentences_completed', models.IntegerField(default=0)),
                ('perfect_sentences', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sentence Builder Game Session',
                'verbose_name_plural': 'Sentence Builder Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentenceBuilderSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(help_text='The complete correct sentence')),
                ('hint', models.TextField(blank=True, help_text='Optional hint for the sentence')),
                ('word_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='core.sentencebuilderlevel')),
            ],
            options={
                'verbose_name': 'Sentence Builder Sentence',
                'verbose_name_plural': 'Sentence Builder Sentences',
                'ordering': ['level__level_number', 'word_count'],
            },
        ),
        migrations.CreateModel(
            name='UserColorProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('perfect_matches', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_splash_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Color Splash Progress',
            },
        ),
        migrations.CreateModel(
            name='UserGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level', models.IntegerField(default=1)),
                ('total_moves', models.IntegerField(default=0)),
                ('games_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Game Progress',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('preset_avatar', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSentenceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('total_sentences', models.IntegerField(default=0)),
                ('perfect_sentences', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Sentence Progress',
            },
        ),
        migrations.CreateModel(
            name='CaptureWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (3-6 years)'), ('medium', 'Medium (7-9 years)'), ('hard', 'Hard (10-12 years)')], max_length=10)),
                ('hint', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_words', to='core.capturepartofspeech')),
            ],
            options={
                'verbose_name': 'Capture Word',
                'verbose_name_plural': 'Capture Words',
                'ordering': ['word'],
                'unique_together': {('word', 'part_of_speech', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('hint', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_words', to='core.searchwordcategory')),
            ],
            options={
                'verbose_name': 'Search Word',
                'verbose_name_plural': 'Search Words',
                'ordering': ['word'],
                'unique_together': {('word', 'category')},
            },
        ),
    ]
