# Generated by Django 5.2.4 on 2025-11-03 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathGameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('operations', models.JSONField(default=list)),
                ('number_range_min', models.IntegerField(default=1)),
                ('number_range_max', models.IntegerField(default=10)),
                ('problems_required', models.IntegerField(default=10)),
                ('time_limit', models.IntegerField(default=180)),
                ('points_per_problem', models.IntegerField(default=10)),
                ('unlock_score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='MathGameProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.CharField(max_length=100)),
                ('correct_answer', models.IntegerField()),
                ('operation', models.CharField(max_length=5)),
                ('hint', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.mathgamelevel')),
            ],
            options={
                'ordering': ['level__level_number'],
            },
        ),
        migrations.CreateModel(
            name='MathGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('current_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('problems_completed', models.IntegerField(default=0)),
                ('perfect_streak', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Math Game Session',
                'verbose_name_plural': 'Math Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMathProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('total_problems', models.IntegerField(default=0)),
                ('perfect_streaks', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Math Progress',
            },
        ),
    ]
