# Generated by Django 5.2.4 on 2025-11-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quizcategory_quizgamesession_quizlevel_quizquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordSearchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('total_words_found', models.IntegerField(default=0)),
                ('perfect_puzzles', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_search_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Word Search Progress',
            },
        ),
        migrations.CreateModel(
            name='WordSearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='🔍', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Word Search Category',
                'verbose_name_plural': 'Word Search Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WordSearchGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('current_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('words_found', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('perfect_puzzles', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word Search Game Session',
                'verbose_name_plural': 'Word Search Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordSearchLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('grid_size', models.IntegerField(default=8)),
                ('word_count', models.IntegerField(default=8)),
                ('time_limit', models.IntegerField(default=180)),
                ('points_per_word', models.IntegerField(default=10)),
                ('unlock_score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='WordSearchPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('words', models.JSONField()),
                ('grid_data', models.JSONField()),
                ('word_positions', models.JSONField()),
                ('hints', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='core.wordsearchcategory')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='core.wordsearchlevel')),
            ],
            options={
                'ordering': ['level__level_number', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='SearchGameSession',
        ),
        migrations.DeleteModel(
            name='SearchWord',
        ),
        migrations.DeleteModel(
            name='SearchWordCategory',
        ),
    ]
